sudo: required
services: docker
before_install:
  - docker build -t al02659529/docker-test -f Dockerfile.dev .
script:
  - docker run al02659529/docker-test -e CI=true npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-969011410218"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"